image: maven:3.3.3

pipelines:
  branches:
    master:
      - step:
          script:
          - mvn clean install -V -B -s settings.xml deploy
    develop:
      - step:
          script:
          - mvn clean install -V -B -s settings.xml deploy